spring:
  datasource:
    druid:
      # 地址
      url: jdbc:mysql://127.0.0.1/database?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      # 账号
      username: username
      # 密码
      password: password
      # 驱动器
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化连接数大小
      initial-size: 3
      # 最大连接数
      max-active: 10
      # 最小连接数
      min-idle: 3
      # 连接超时时间
      max-wait: 60000
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.briefing.summary.service.*
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
mybatis:
  #  type-aliases-package: com.briefing.*.model
  #  mapper-locations: classpath:com/briefing/*/dao/*Mapper.xml
  configuration:
    # 驼峰式命名自动转换
    map-underscore-to-camel-case: true


